### PR TITLE
Custom environment variable generator tool for the truly lazy

### PR DESCRIPTION
**Pull request by matthewadams**
After issue https://github.com/lorenwest/node-config/issues/218 was closed, I got kind of high & mighty, creating a tool to do this grunt work for me.  I'm now contributing it back because there have to be others who are as lazy or lazier than me.

The gist is as follows.  Massage how the tool is attached to `config`'s `module.exports` however you want.  I hope you like it.
```
var fs = require('fs');
var config = require('config');
var tool = config.cev; // if you don't want the tool to be available this way, I understand...

fs.writeFileSync(
  'config/custom-environment-variables.json',
  JSON.stringify(
    tool.generate(config, { prefix: 'MYAPP' }),
    0, 2));
```

### CODE REVIEW

**Comment by lorenwest** [comment]
I really appreciate the amount of effort you put into this, and the test class to go along with it.  Your perspective is probably different, but from the every day node-config usage, this is an edge case of an edge case.

In an effort to minimize and simplify, I think this would be an excellent add-on to node-config.  I would wholeheartedly support this as a separate node module, with a link to it in the wiki describing custom configs.

**Comment by matthewadams** [comment]
Hi Loren,

It's not really *that *big a deal.  Only took me about 1.5 hrs.  I only did
it because I'm so freaking lazy.  :)

I'll see if we can publish it as its own module and let you know.

-matthew

On Tue, Jun 9, 2015 at 11:50 PM, Loren West <notifications@github.com>
wrote:

> I really appreciate the amount of effort you put into this, and the test
> class to go along with it. Your perspective is probably different, but from
> the every day node-config usage, this is an edge case of an edge case.
>
> In an effort to minimize and simplify, I think this would be an excellent
> add-on to node-config. I would wholeheartedly support this as a separate
> node module, with a link to it in the wiki describing custom configs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/pull/222#issuecomment-110588054>
> .
>



-- 
mailto:matthew@matthewadams.me <matthew@matthewadams.me>
skype:matthewadams12
googletalk:matthew@matthewadams.me
http://matthewadams.me
http://www.linkedin.com/in/matthewadams

**Comment by matthewadams** [comment]
FYI, forked repo has been deleted.  I'm not working on making this a standalone tool.  More information to come later when I'm done.

**Comment by matthewadams** [comment]
Hey Loren,

This is now published in the public NPM repo at https://www.npmjs.com/package/config-cev-generator.

Blog post is at http://www.scispike.com/blog/get-rid-of-node-js-config-grunt-work

SciSpike's social media streams will be announcing it on Monday.  Link to anything you'd like to!

**Comment by lorenwest** [comment]
Sweet!  I've added a [Community Utilities](https://github.com/lorenwest/node-config/wiki/Community-Utilities) section of the wiki with a link to the CEV generator.  You're welcome to edit that page to change the description if you'd like.

**Comment by matthewadams** [comment]
worksforme :)

On Mon, Aug 24, 2015 at 8:55 AM, Loren West <notifications@github.com>
wrote:

> Sweet! I've added a Community Utilities
> <https://github.com/lorenwest/node-config/wiki/Community-Utilities>
> section of the wiki with a link to the CEV generator. You're welcome to
> edit that page to change the description if you'd like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lorenwest/node-config/pull/222#issuecomment-134212204>
> .
>



-- 
mailto:matthew@matthewadams.me <matthew@matthewadams.me>
skype:matthewadams12
googletalk:matthew@matthewadams.me
http://matthewadams.me
http://www.linkedin.com/in/matthewadams

**Pull request closed without merging**
