### PR TITLE
Git crypt support

### PR DESCRIPTION
**Pull request by cunneen**
Reissue PR #375 with tests. Adds git-crypt support. See #375 for discussion, and [the wiki entry](https://github.com/lorenwest/node-config/wiki/Securing-Production-Config-Files) for more info.

### CODE REVIEW

**Comment by lorenwest** [comment]
Thank you for the work you've put into this commit.

**Comment by lorenwest** [comment]
Published at config@1.25.0

**Comment by cunneen** [comment]
You're most welcome; thank you for sharing your project!

**Comment by lorenwest** [comment]
@cunneen - Can you comment on https://github.com/lorenwest/node-config/pull/377 ?

Welcome to becoming the owner of all git-crypt related issues :)

**Pull request merged**
