### PR TITLE
Fix #628: node_env_var_name is not defined

### LINKED ISSUE #628: Uncaught ReferenceError: node_env_var_name is not defined
### What is the current behavior?

I am currently seeing this bug in 3.3.3 in the browser:

```
Uncaught ReferenceError: node_env_var_name is not defined
    at j._.loadFileConfigs
```

Screen Shot 2020-11-30 at 8 19 37 PM

It appears it is from this commit:

b4ba63c84ec9b3d86559bca05b34f78833f3f850

In this line:

https://github.com/lorenwest/node-config/commit/b4ba63c84ec9b3d86559bca05b34f78833f3f850#diff-d5109920b34c2b2e141bd41232d8876432a17479c388e142d8a036bb7b36ea62R520

### What is the expected behavior?

Previous versions of node-config would not throw this error.

### Please tell us about your environment:

 -  node-config version: 3.3.3 
 -  node-version: 12.18.3
 
### Other information

Webpack config:

```js
const webpack = require('webpack');
const config = require('config');

const getNodeConfigPlugin = (addPlugin) => {
  const CLIENT_CONFIG = {
    app: {
      gitSha: config.get('app.gitSha'),
    },
    env: {
      nodeEnv: config.get('env.nodeEnv'),
    },
    performance: config.get('performance'),
  };

  console.warn(
    CLIENT_CONFIG,
    'WARNING: THIS CONFIGURATION INFORMATION WILL BE AVAILABLE TO THE CLIENT'
  );

  addPlugin(
    new webpack.DefinePlugin({
      'process.env.NODE_CONFIG': JSON.stringify(JSON.stringify(CLIENT_CONFIG)),
    })
  );
};
exports.getNodeConfigPlugin = getNodeConfigPlugin;
```

### PR DESCRIPTION
**Pull request by prnake**

### CODE REVIEW

**Review by lorenwest — APPROVED** [review]

**Comment by lorenwest** [comment]
Thanks for the fix.  I'll release a point version asap.

**Comment by seSze** [comment]
When do you expect this to be done?

**Comment by lorenwest** [comment]
It was pushed in v3.3.5 yesterday.

**Comment by aloudmind** [comment]
When will the 3.3.5 version be released?

**Comment by lorenwest** [comment]
Thank you @aloudmind. I thought you were being sarcastic, because, the comment right above yours.  Turns out I published it to the wrong repository because my local .npmrc was pointing to a different one.  Changed package.json to specify the public registry, so it fails if trying to publish to a different one.

Published to public npm repository on v3.3.6 today :)

**Pull request merged**
