### PR TITLE
fix bug when user does export CONFIG_SKIP_GITCRYPT env

### PR DESCRIPTION
**Pull request by ramimoshe**
Fix exception:

ReferenceError: CONFIG_SKIP_GITCRYPT is not defined
at util.loadFileConfigs (/usr/local/jive/servers/realtime/lib/node_modules/rt/lib/v2/services/connector/node_modules/config/lib/config.js:651:24)
at new Config (/usr/local/jive/servers/realtime/lib/node_modules/rt/lib/v2/services/connector/node_modules/config/lib/config.js:122:27)
at Object.<anonymous> (/usr/local/jive/servers/realtime/lib/node_modules/rt/lib/v2/services/connector/node_modules/config/lib/config.js:1735:31)

### CODE REVIEW

**Comment by markstos** [comment]
@ramimoshe your proposed fix causes a test suite failure. Could you investigate?

**Comment by ramimoshe** [comment]
Ok, I can add one more test case with unset env
But the problem that I have is:
I updated my project to the latest node-config 
so I dont have this env 
and then I tried to run my project, and I got an exception

you can try it in your project

**Comment by markstos** [comment]
@ramimoshe I believe you there's a significant issue with the latest release because the test coverage wasn't sufficiently good last time around. 

That's why I'm especially interested that the follow-up fix is of high quality with good test coverage and commit messages for the next update to be especially clear what's happening.

**Comment by lorenwest** [comment]
It appears this only happens in runtime environments that restrict the use of global variables, which is why Travis didn't catch it. The problem was a leaked variable into global scope. I think I've fixed the problem, but @ramimoshe would you mind verifying that 1.25.1 resolves your issue?

**Comment by cunneen** [comment]
This looks like a good test to add (CONFIG_SKIP_GITCRYPT=0). I agree with @markstos that it should be in addition to the existing tests, rather than replacing them.

Apologies for the inconvenience caused by omitting the var declaration in PR #376 ; for some reason I had the declaration uncommitted in my local repo. Thanks @lorenwest for cleaning it up.

**Pull request closed without merging**
