### PR TITLE
Standard JS integration

### PR DESCRIPTION
**Pull request by tusharmath**
Fixes : #305

### CODE REVIEW

**Comment by markstos** [comment]
@tusharmath this pull request doesn't pass our Travis tests because there are hundreds of StandardJS failures.

**Comment by tusharmath** [comment]
@markstos That's the intent. You know when to merge, when all the issues are fixed.

**Comment by tusharmath** [comment]
Total Errors: `1935`

**Comment by tusharmath** [comment]
Total Errors: `232`

**Comment by tusharmath** [comment]
@markstos Take a look at the errors. Apart from style errors, it has also highlighted errors such as — using *undeclared variables* , using *==* instead of *===*. This could lead to potential issues in production.

**Comment by tusharmath** [comment]
@markstos There is one particular failure —

```bash
/node-config/lib/config.js
  247:40  error  'fnName' is not defined
```
I am not sure how to fix it. May be you can help me here?

**Comment by lorenwest** [comment]
That's a straight-up bug.  Instead of

```
...config.' + fnName + '()...
```

It should be

```
...config.watch()...
```

It looks like that code was copied from a more generic place into the watch function, without making it specific to watch().

**Comment by lorenwest** [comment]
This PR has too many changes.  Is there a way to change a configuration such that the errors are significantly reduced to match the coding style of the package, and the only errors are real improvements like ```==``` to ```===``` ?

**Comment by tusharmath** [comment]
@lorenwest No we can't configure it. Check the [FAQ](http://standardjs.com/index.html#i-disagree-with-rule-x-can-you-change-it).

If the changes are too big to review, I would recommend you go commit by commit. That way u will be able to review all the changes.

**Comment by tusharmath** [comment]
@lorenwest Some weird issue on node `0.8` can you try re-running after clearing cache on travis?

**Comment by tusharmath** [comment]
Looks like the issue was with `snazzy` module which doesn't work with version `0.8` because of its dependency on `inherits` module. I have removed it for now as it just a prettfier for standardjs's output. Once the issue is fixed, I guess we can re-integrate it later.

PS: Build is fixed!

**Comment by lorenwest** [comment]
This was a large amount of work and as much as I dislike the size of the PR, the point is to endure some pain in order to achieve consistency.

My concern is that manual changes are intermixed with automated changes, making it impractical to detect the changes due to reformatting vs. the changes due to manual code. Normally that'd be mitigated by tests, but the tests were changed along with the code.

My suggestion to getting this merged is to split the work into multiple pull requests:

1) All manual changes needed
2) Automated changes to lib/config.js alone, showing existing tests pass
3) Automated changes to the rest of the package, including tests
4) Travis hooks so earlier commits don't break travis

I sincerely appreciate the work you've put into this and the consistency it brings to the library. If you can break it into these multiple commits, I will take the time necessary to get them committed and pushed to NPM once they're all in.

-Loren

**Comment by tusharmath** [comment]
Closing this infavour of https://github.com/lorenwest/node-config/pull/310

**Pull request closed without merging**
