### PR TITLE
Add info about IntelliJ-plugin.

### PR DESCRIPTION
**Pull request by annitya**
A shameless plug from yours truly here.

The plugin provides references between usage of node-config and the config-files themselves.
This allows for code-completion, find-usages, rename-refactoring and the like.

While still in its infancy, I believe it should provide a little productivity boost already now.

### CODE REVIEW

**Comment by markstos** [comment]
The screenshot shows on the plugin page is a bit weird:
https://plugins.jetbrains.com/plugin/10381-nodeconfig

First, I think it's most common to import `config` with the name `config`,
but `stats_db` is used here. Second, config values are usually accessed
with `config.get('some-name')`, but the autocomplete seems to promoting
direct access to the configuration property names, which is discouraged The
autocompletion that people are most likely to want-- `get()`-- does not
appear in the list.

**Comment by whitefire** [comment]
I modeled the usage-pattern after that of our organization. Seems we've been doing it wrong...

No worries though, that can easily be remedied :)
Would you prefer I remove all support for direct-access all together or keep it as an alternative?

**Comment by markstos** [comment]
Usually calling `config.get()` or `config.has()` is a much better option than direct access. You could continue to provide it if you want, but I think it could primarily serve to add confusion.

**Comment by whitefire** [comment]
Best practice is the way to go. I will make adjustments! :)

**Comment by annitya** [comment]
Well... it sure took me long enough, but version 2.0 is now awaiting approval from JetBrains.
I don't know if you're an IntelliJ man yourself, but the new version is available for testing [here](https://github.com/annitya/nodeconfig/blob/2.0/node-config.jar).

image

Hopefully I didn't lure too many developers to the dark side in the meantime. Old format-support is not only removed, I also added an inspection highlighting non-recommended usage for good measure.

**Comment by lorenwest** [comment]
What do you think @markstos ? I'm appreciative of the work @annitya put into this, including your suggested changes.

**Comment by markstos** [comment]
@annitya The testing link is 404. When it's working,I'll have some co-workers who use WebStorm test.

**Comment by annitya** [comment]
Which link are you referring to?

**Comment by markstos** [comment]
@annitya https://github.com/annitya/nodeconfig/blob/2.0/node-config.jar is 404 for me.

**Comment by annitya** [comment]
Ah, now I understand what you mean. You needn't download the plugin from GitHub, just install it like you would any other plugin. Let me know of any improvements I can make, and of course if you find a bug! :)

**Comment by markstos** [comment]
@annitya I had my co-worker install version 2.0.2 of the plugin. I saw that it completed the raw property names, but it not values within `config.get()` as seen in your screenshot. 

Regardless, @lorenwest I think the more appropriate place to add this would be on the "Community Utilties" wiki page, rather than in the README. Would you agree?

https://github.com/lorenwest/node-config/wiki/Community-Utilities

**Comment by lorenwest** [comment]
Yes, add to community utilities page.

**Comment by markstos** [comment]
@annitya I believe you edit the related wiki page directly, so I'm closing this PR.

**Pull request closed without merging**
