### PR TITLE
Allow all defined values in `substituteDeep`

### PR DESCRIPTION
**Pull request by fostyfost**

### CODE REVIEW

**Comment by lorenwest** [comment]
Thank you for this contribution. It appears to be an improvement in that the current implementation doesn't allow all values (specifically, other falsey values like numeric 0 and the "" empty string).

I support this change, and since it will cause a slight behavior change I think it would be appropriate to add a test that outlines the problem. One that has a list of items to substitute including some non-undefined falsey values, and verifies that these values make their way into the substitution.

In the unlikely case that someone was relying on this side-effect, the test will show the problem clearly, and will be hard to argue that this shouldn't be considered correct behavior for substituteDeep.

**Comment by markstos** [comment]
Looks good to me too.

**Comment by fostyfost** [comment]
@lorenwest @markstos 
Hello, I added the tests you requested.

**Comment by lorenwest** [comment]
Published today on `node-config@3.3.0`

**Comment by wham** [comment]
This is definitely a change in the right direction. But it seems to be backwards incompatible and as such would deserve a major version update or at least a better description on the changelog. Given that environment variables are not strongly typed, I think it's a pretty common scenario to use `""` as _not set_.

**Pull request merged**
