### PR TITLE
Eslint Integration

### PR DESCRIPTION
**Pull request by tusharmath**

### CODE REVIEW

**Comment by tusharmath** [comment]
@lorenwest Could you please take a look at the errors — https://travis-ci.org/lorenwest/node-config/jobs/123596668

I have added all the configs as per my understanding. I would need your inputs to figure out what should be changed in the code vs config.

**Comment by lorenwest** [comment]
Yes, I see the lint errors. Anyone want to take on the work of cleaning these up? You'll be listed in high regard as a contributor on our README page :)

**Comment by markstos** [comment]
@antony see the PRs #305 and #307 which already started work on being `standard` compliant. It seems this PR is a third iteration of that work. I have not reviewed what the remaining issues were recently, but they should be found somewhere in these 3 pull requests.

**Comment by antony** [comment]
Ah, interesting. So ESLint is being preferred to standard. That's a shame, as it allows configuration and personal preference which results in endless, resolution-less debates. However! The people have spoken :)

**Comment by markstos** [comment]
As a maintainer, I'm in favor of using eslint. I just assume to follow the "AirBnB" rules to address @antony point about debates about all the details. I also think "Pretty" may be a better choice for code formatting, while Eslint is better suited for code syntax issues.

Also, I think make `eslint` should be run as part of `npm test`

I would be interested in PR that adds Eslint inegration along with a commit that addresses all the eslint violations that are triggered when adopting it.

**Comment by jdmarshall** [comment]
#667 Fixes a handful of these issues.

**Comment by markstos** [comment]
Closing due to lack of volunteer to fix the linting errors in the past 5 years.

I like the idea of using `prettier` for code formatting issues and `eslint` for code-style issues, following the `AirBnB` rules. An updated attempt to introduce `prettier` or `eslint` along with resolving the errors the flag is welcome.

**Comment by jdmarshall** [comment]
The changes I made in my first PR were based on Webstorm complaints. I haven't been keeping track of their release notes so at this point I couldn't say whether they're using third party code or something they invented.

**Pull request closed without merging**
