### PR TITLE
#570 - Improved error handling of env variables value parse

### PR DESCRIPTION
**Pull request by leonardovillela**
https://github.com/lorenwest/node-config/issues/570

### CODE REVIEW

**Comment by markstos** [comment]
Looks good to me.

**Comment by leonardovillela** [comment]
anyone more needs to revise my PR?

**Comment by lorenwest** [comment]
Thank you @leonardovillela, and apologies for it taking a while to get through. Been busy!!

Published to NPM today on config@3.2.4

**Comment by leonardovillela** [comment]
I'm glad to help.

**Pull request merged**
