### PR TITLE
Support optional default value in the get method

### PR DESCRIPTION
**Pull request by kureci**
and tests to cover the change

### CODE REVIEW

**Comment by kureci** [comment]
This is my first fork/PR on an open source project, ever! So please be nice :)

**Comment by markstos** [comment]
@kureci I appreciate you are getting involved with open source. 

In the future, I recommend searching the issue tracker and previous PRs before submitting one, because this request is a duplicate of a requests/PR that has already been submitted and rejected  a number of times. The most recent being #442  You can read more about the rationale, there. 

Although this PR was not accepted, the fact that you added test coverage is something that would increase the chances that a project will accept a PR from you in the future. It's also helpful to update the documentation when you add a new feature as well.

**Comment by kureci** [comment]
I understand the rationale you've given in #442, and we've also had the same discussions with my work colleagues. However, there are also cases where you should be allowed to just accept a default if no config exists for it. These can be non-critical config parameters that is nice to have in configuration but not absolutely necessary. 

Allowing to have default values in code isn't the same as supporting the use of it. We should still discourage using the functionality in most cases, but still give people the option for rare cases. This is especially true for fast-paced environments where CI/CD is key; when you use configuration management tools like Puppet and it takes a bit longer to deploy configuration changes to environments (for various reasons), such restriction blocks application code to be deployed before configuration without breaking something (i.e. the exception thrown in this case).

Many people would discourage using `static` methods in most cases, but that doesn't mean you should remove the ability to create static methods in a language.

**Comment by kureci** [comment]
That being said, I now see my issue. The module neatly allows the use of `default.json` file which can/should really be in your repo that overcomes the hurdle I described above. My problem was how I didn't want to have `default.json` in the repo, but now I see the benefit. 

Now I agree with you :)

**Comment by markstos** [comment]
For clarity of *all* the config options, I recommend putting *every* config value in `config/default.js`, including optional values.

I don't understand how an environment is both "fast paced"  yet "takes longer to deploy changes". 

Since the feature add default values to `config.get()` doesn't exist, I know that my team isn't using it to sprinkle config values througout the code.  There is already Lodash `_.get()` if you want put default values in functions that for some reason don't seem to belong in central configuration.

**Comment by kureci** [comment]
"fast-paced" !== "everything is deployed at the same time" ;)

**Pull request closed without merging**
