### PR TITLE
test with a more complex quote

### PR DESCRIPTION
**Pull request by adityabansod**

### CODE REVIEW

**Comment by lorenwest** [comment]
Sweet - thanks!  I'm going to merge this in, knowing it fails the Travis CI, in preparation for either a rollback or bugfix soon (as in today).

**Comment by adityabansod** [comment]
:+1:

**Comment by markstos** [comment]
I vote for rolling back the JSON change until a better fix is available.

**Comment by lorenwest** [comment]
If @elliotttf or someone appears soon with a fix to this, that would be a little better than a rollback.  I'm thinking about doing a rollback in a couple hours if this isn't resolved by then.

**Comment by elliotttf** [comment]
That's a bummer, I'm looking into this, but as I mentioned in #256 anything we do with regexes is liable to be brittle.

**Comment by elliotttf** [comment]
#261 should resolve this.

**Pull request merged**
