### PR TITLE
Add method to output plain JS object

### LINKED ISSUE #223: Add a method for outputting a plain JS object (PR welcome)
Feature request:  

I think it would really benefit this module to formalize the output of a plain javascript object. I know the little one-liner `JSON.parse(JSON.stringify())` but boy, that feels like an opaque weird thing to have in my app code. The need for POJOs is frequent, for instance, using the hapijs server if I attempt to bring any `node-config` object into a config, hapi will fail on the schema validations because of all the additional methods.

Other libraries, such as immutable, that do large amounts of manipulation on objects offer a `toJS` method, which makes a lot of sense to me. As a stop-gap that method could just do the parse/stringify trick, but I think ideally it would access the hidden internal variables and output those directly.

Going even further, I'd make the case that _any_ invocation of `.get()` should actually output a POJO. It feels highly unnatural to me to be carrying around all this baggage when I've clearly made the choice to only grab a portion of my config.

### PR DESCRIPTION
**Pull request by willsoto**
Closes #223

I will be happy to add this to the Wiki if this is acceptable.

PS: I saw #426, but it looks abandoned, so I did it here taking into consideration [this comment](https://github.com/lorenwest/node-config/issues/223#issuecomment-112951557)

### CODE REVIEW

**Comment by willsoto** [comment]
Looks like the CI error has something to do with Node 4? 

https://travis-ci.org/lorenwest/node-config/jobs/288266571#L462

**Comment by lorenwest** [comment]
This code looks good - thanks for the addition. It's an old thread, and I'm glad someone who needed the functionality added it.

The failure appears to be a NodeJS versioning problem. I'll see if I can get it working again.

**Comment by lorenwest** [comment]
Got it working. Rebase and re-submit, and I'll get it merged.

**Comment by willsoto** [comment]
@lorenwest Thanks for that! I'll take of that this evening and ping you.

**Comment by willsoto** [comment]
@lorenwest That did it. Rebased and CI is green.

**Comment by willsoto** [comment]
I will also have some time tonight to add this to the Wiki (if that is still desirable). Would [this](https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities) be the right page for it?

**Comment by lorenwest** [comment]
Yes, that would be the perfect page for it.  Thanks for the update!

**Comment by lorenwest** [comment]
Published changes today on v1.27.0

**Comment by markstos** [comment]
@willsoto Thanks for the contribution. Did you also add docs for `.toObject()?` I don't see it mentioned in the README or on the wiki.

**Comment by willsoto** [comment]
https://github.com/lorenwest/node-config/wiki/Using-Config-Utilities#toobjectconfig

**Comment by markstos** [comment]
Thanks.   Perhaps we should also add an FAQ page  as well. Someone just ran
into this and posted on StackOverflow:

https://stackoverflow.com/questions/48867065/typeerror-key-must-be-a-buffer-when-sending-an-email-with-aws-sdk-in-node-js/49032379#49032379

Essentially, they want to know "Is node-config missing with my data? Why?
How do I fix it?".

The function docs for `toObject()` are only useful once you've realized
precisely that you need such a method. As seen on #223, there have been
about 10 different related issues opened.

Maybe we just need to be more up front to explain that node-config is going
to add some methods to objects it turns, along with the solution for
getting rid of the extra methods if you don't want them.

**Pull request merged**
