### PR TITLE
Add support for experimental modules (rebased)

### PR DESCRIPTION
**Pull request by lenkan**
https://github.com/lorenwest/node-config/pull/586 has been blocked by a conflict for some time. This PR resolves that conflict with a rebase.

### CODE REVIEW

**Comment by markstos** [comment]
Looks good. I see there's already a mention o the wiki about this, so it's all set to merge. 

https://github.com/lorenwest/node-config/wiki/Configuration-Files#commonjs-javascript-module---js-cjs

**Comment by lenkan** [comment]
Thanks @markstos 

Do you think you will get around to publish 3.4.0 for this anytime soon? Let me know if there is something I can do do help.

**Comment by markstos** [comment]
@lenkan Usually @lorenwest publishes the releases.

**Comment by lorenwest** [comment]
Thanks for the ping. Lots of improvements lately - will prepare and publish over the holiday weekend.

**Comment by lorenwest** [comment]
Published today at v3.3.3

**Pull request merged**
