### PR TITLE
one small dev for man, one giant leap for mankind

### PR DESCRIPTION
**Pull request by Yagora**
Hey,

Can you merge this ? It's better to use the environnement variable for the different distribution.
I can't build anymore my distrib without this changement.

Thank you

### CODE REVIEW

**Comment by markstos** [comment]
Looks good.  Merging.

**Comment by lorenwest** [comment]
This script is intended to be run just before an npm deployment. As far as I know there's only one person that runs this script.

I'm curious: what sort of build environment do you have that runs this script?

It is a healthy change though - thanks for submitting the PR.

**Comment by Yagora** [comment]
Hi,

I build my own distribution with Yocto Project and my node binary isn't in /usr/local/bin/node.

I think it's a good way to use the environnement variable to resolve the binary path :)

Tanguy

**Comment by Yagora** [comment]
Excuse me, why this PR is closed ?

**Comment by markstos** [comment]
@Yagora according to the history of the issue published above, the PR was merged, and thus closed.

**Pull request closed without merging**
