### PR TITLE
💥(deprecation): remove config.watch and global utils

### PR DESCRIPTION
**Pull request by jpwilliams**
~The util.watch deprecation message was using a variable that was undefined.~

---

Remove deprecated methods for `v2.0.0`.

### CODE REVIEW

**Comment by lorenwest** [comment]
Thank you for finding this. I guess it shows how many people actually use this method.

Instead of this pull request, I think it's best to remove all deprecated functionality.

**Comment by lorenwest** [comment]
Like a breath of fresh air...

Yes, I'd like that. There's at least one other place that refers to deprecation. They've been in there for years, so now's a great time to purge.

**Comment by jpwilliams** [comment]
Sure. Let me get my hammer out and see if I can find the right bits for you.

**Comment by lorenwest** [comment]
Thanks for the cleanup. I'll get this published soon.

**Comment by lorenwest** [comment]
Published in 2.0.1.  Thanks for the contribution!

**Comment by markstos** [comment]
`deferConfig` is actively used and documented on the wiki: 

https://github.com/lorenwest/node-config/wiki/Special-features-for-JavaScript-configuration-files#deferred-values-in-javascript-configuration-files

**Comment by jpwilliams** [comment]
@markstos It is, but is `require`d directly via `require('config/defer')`.

I'm refering to the `require` in [lorenwest/node-config/lib/config.js:17](https://github.com/lorenwest/node-config/blob/master/lib/config.js#L17) which is never used or exported.

**Comment by markstos** [comment]
@jpwilliams I see that now. The project has a quite a number of issues caught by a linter:

```
   17:5   error  'deferConfig' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/          no-unused-vars
    26:5   error  'NODE_CONFIG' is defined but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                   no-unused-vars
    27:21  error  'ALLOW_CONFIG_MUTATIONS' is defined but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/        no-unused-vars
    29:5   error  'privateUtil' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/          no-unused-vars
    30:5   error  'deprecationWarnings' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/  no-unused-vars
   158:7   error  't' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                    no-unused-vars
   415:9   error  'value' is already defined                                                                                             no-redeclare
   458:7   error  't' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                    no-unused-vars
   525:7   error  't' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                    no-unused-vars
   727:7   error  't' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                    no-unused-vars
   890:19  error  Empty block statement                                                                                                  no-empty
  1007:7   error  't' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                    no-unused-vars
  1187:9   error  'msg' is not defined                                                                                                   no-undef
  1188:21  error  'msg' is not defined                                                                                                   no-undef
  1233:7   error  't' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                    no-unused-vars
  1300:7   error  't' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                    no-unused-vars
  1347:7   error  't' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                    no-unused-vars
  1512:7   error  't' is assigned a value but never used. Allowed unused vars must match /^_$|^log$|^defer$|^moment$/                    no-unused-vars
```

Those all seem  safe to clean up. @jpwilliams  Interested in putting together a new PR to clean-up linting violations and add an .eslintrc to the project for us?

**Comment by jpwilliams** [comment]
Sure thing - would love to help out! I'll see if I get time in the day tomorrow. 👍

**Pull request merged**
