### PR TITLE
Issue #338 Adding raw wrapper to prevent object modification in config

### PR DESCRIPTION
**Pull request by patrickpilch**
Looking for feedback on whether this is an acceptable solution that will cover all the scenarios. (e.g. does `util.cloneDeep` have relevance to this?)

**TODOS**

1. Improve test
2. Documentation in the Wiki

### CODE REVIEW

**Comment by lorenwest** [comment]
This looks good to me, but I want @markstos to review to see if it follows the patterns he used for defer.

**Comment by markstos** [comment]
This looks good to me to, and does appear to mirror the pattern used for defer, so I think it will feel familiar both for users and contributors. I'm merging now. 

@patrickpilch Could you go ahead and document this feature on the wiki? https://github.com/lorenwest/node-config/wiki/Configuration-Files#javascript-module---js    We'll try to cut a release about the same time.

Thanks for the contribution!

**Comment by patrickpilch** [comment]
@markstos I've added the documentation

**Comment by markstos** [comment]
Looks good to me. @lorenwest  I think this is ready for merge-and-release.

**Comment by sylvainv** [comment]
Was this merged ? It is in the documentation on master, but cannot actually be used because there is no `raw.js` file.

**Comment by patrickpilch** [comment]
@markstos What is the status of this PR?

**Comment by markstos** [comment]
@patrickpilch @sylvainv It has been merged now and is pending release by @lorenwest

**Comment by lorenwest** [comment]
Published 10/25 in 1.22.0

**Pull request merged**
