### PR TITLE
node-config/#211 Enable environment variables to be parsed in a specified format

### PR DESCRIPTION
**Pull request by leachiM2k**

### CODE REVIEW

**Comment by lorenwest** [comment]
Hi @leachiM2k, just now getting to the merge.  This is a big pull request - 142 additions and 76 deletions.  I know there weren't that many changes - is there a way to structure your changes so just your additions/deletions are in the pull request?

Take a look at the [file changes](https://github.com/lorenwest/node-config/pull/213/files) page to see what I mean - it's hard to see the changes you've made.

Thanks,
-Loren

**Comment by leachiM2k** [comment]
Hey Loren,
thank you for taking a look at it. Actually, I had to refactor the method util.parseFile to reuse the format parsing technique for environment variables. I extracted the non-file based formats to a new method called util.parseString. This is where all the changes come from.
Do you have a better idea how to structure the pull request? Maybe by splitting it up into two (refactoring and env var parsing)?

**Comment by lorenwest** [comment]
That's a good plan.  First submit the refactor, then the code that uses it.

Thanks,
-Loren

**Comment by leachiM2k** [comment]
Ok, as you can see, that commit contains only changes for this feature now.

**Comment by lorenwest** [comment]
Thanks again for your patience while I got to this.  It looks good.  I'm going to merge it into master, but before I push a new release it will need to be documented on the wiki.  Would you mind taking a stab at it and letting me know which page it's placed within?

**Comment by leachiM2k** [comment]
Hey Loren, thank you for your time.
I've added an example and a description for this new behavior on [Environment Variables Wiki](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables)
Feel free to change the "coming release" to the right version.

**Pull request merged**
