### PR TITLE
Feature : Add default value to get method

### PR DESCRIPTION
**Pull request by AbderrahimSoubaiElidrissi**
Now you can set the default value of a property 

````
var config = require('config');
// with localhost here as default value of  Customer.dbConfig.Host if is null or undefined
var dbConfig = config.get('Customer.dbConfig.Host', 'localhost');

````

### CODE REVIEW

**Comment by lorenwest** [comment]
This issue has a sorted history. Search for 'default' in issues and you'll see threads and threads of discussion.  Here's one: https://github.com/lorenwest/node-config/issues/504

**Comment by markstos** [comment]
It's surprising how many people submit basically the same pull request without first searching for existing issues and pull requests first.

**Comment by markstos** [comment]
Also see #381, #393 and #462.

**Comment by lorenwest** [comment]
To be fair, defaulting on get() appears to be an obvious omission to the newcomer, and it pains me to see people putting effort into this, just to be rejected by those of us that see it so many times.

I would accept a pull request with a comment near Config.prototype.get() that describes the issue, with a search URL for more info.

**Comment by markstos** [comment]
I agree it could be a helpful hint for the next person who considers adding the feature.

**Pull request closed without merging**
