### PR TITLE
Fix `TypeError: obj.toString is not a function` in lib/config.js:1287:36

### PR DESCRIPTION
**Pull request by leosuncin**
Solves lorenwest/node-config#564

### CODE REVIEW

**Comment by leosuncin** [comment]
Call `toString` method from `Object.prototype` in case when the argument `obj`doesn't implement it

**Comment by iMoses** [comment]
@leosuncin Can you provide a test with it to showcase the problem?

**Comment by leosuncin** [comment]
I created a project with the error https://github.com/leosuncin/lorenwest-node-config-564

**Comment by leosuncin** [comment]
I don't understand what do you ask @iMoses, can you clarify more or give me some examples?

**Comment by iMoses** [comment]
@leosuncin If I understood #564 correctly then the problem looks something like that:
```js
const object = {a: 1};
object.prototype = null;
object.toString() // function doesn't exist
``` 
If our solution is supposed to solve this problem then I think we should have a test proving that it does.

I expected the test to look something like this:
```js
const object = {a: 1};
object.prototype = null;
assert(util.isPromise(object), false);
const promise = Promise.resolve({a: 1});
promise.prototype = null;
assert(util.isPromise(promise), true);
```

**Comment by leosuncin** [comment]
Do you mean sometime like this?
> empties the object's prototype
```js
var obj = Object.create(null);
console.log(obj.__proto__, obj.constructor, obj.toString);
console.log(Object.prototype.toString.call(obj)); // Shows '[object Object]'
```
> empties the promise's prototype
```js
var promise = new Promise(() => {});
console.log(promise.__proto__, promise.constructor, promise.toString());
promise.__proto__ = null;
// from now any test will fail
console.log(promise.__proto__, promise.constructor, promise.toString);
// the previous test doesn't work
console.log(util.isObject(promise) && promise.toString() === '[object Promise]'); // <- Exception will throws
// neither my proposal
console.log(Object.prototype.toString.call(promise)); // Shows '[object Object]'
```
Because `promise.__proto__ = null` overrides the constructor name, this will never happens in normal code, so I think the last one is unnecessary test case

**Comment by iMoses** [comment]
@leosuncin you may be right, but when it comes to tests (simple ones) I'd rather cover more cases.

If you asked me a week ago I wouldn't have thought empty prototypes is something I'd ever have to worry about..

**Comment by leosuncin** [comment]
People will never override promise's `__proto__` because is going to break the promise:
```js
var promise = new Promise(function(resolve) {
  setTimeout(resolve('Hi from the future'), 2000);
});
console.log(promise.constructor.name, promise instanceof Promise, 'then' in promise, typeof promise.then);
promise.__proto__ = null;
console.log(promise.constructor, promise instanceof Promise, 'then' in promise, typeof promise.then);
promise.then(console.info); // Throws an exception
```

**Comment by lorenwest** [comment]
Published today in config@3.2.1

**Pull request merged**
