### PR TITLE
Remove deprecated __lookupGetter__ use

### LINKED ISSUE #313: TypeError: mergeFrom.__lookupGetter__ is not a function (PR welcome)
Node v6 removed the non-standard `__lookupGetter__` method from `Object.prototype`. This causes an application with a default and environment specific config to immediately crash.

`Object.getOwnPropertyDescriptor(mergeFrom, prop).get` is the standard way to access the getter, and `Object.defineProperty(mergeInto, prop, Object.getOwnPropertyDescriptor(mergeFrom, prop))` would properly copy it over.

### PR DESCRIPTION
**Pull request by thetalecrafter**
fixes #313.

### CODE REVIEW

**Comment by thetalecrafter** [comment]
While I tested locally on 4.4.3, the versions in travis threw an exception. I will update to fix.

**Comment by markstos** [comment]
I see from Travis that this passes on  Node 0.8, Node .10 and Node 0.12.

@lorenwest can Travis be updated to also test the Node 4.4, the current LTS releases, as well as Node 6?

**Comment by lorenwest** [comment]
Yes, it's in .travis.yml and that doesn't need an npm push. New commit to any branch will kick off the changes.

**Comment by markstos** [comment]
@lorenwest I've updated .travis.yml now to also test 4.4 and 6.0. Thanks for the reminder on how to configure that.

**Pull request merged**
