### PR TITLE
add soft dependencies

### PR DESCRIPTION
**Pull request by gewentao**
Met the same issue as #345 when trying to bundle code with rollupjs. It seems pr #358, failed test cases, was submitted for resolving this issue and it works for me. So this pr was submitted, thanks!

### CODE REVIEW

**Comment by markstos** [comment]
This looks OK to me.

**Comment by lorenwest** [comment]
Looks good to me - thanks for the addition!

**Comment by lorenwest** [comment]
Published today @1.29.3

**Comment by gewentao** [comment]
Thanks !

**Comment by gewentao** [comment]
Sorry, but It seems this pr was not published within 1.29.3 :)

**Comment by gewentao** [comment]
Sorry, but It seems this pr was not published within 1.29.3 :) @lorenwest

**Comment by lorenwest** [comment]
Second time's a charm? Try 1.29.4.

**Comment by gewentao** [comment]
hah, got it thanks

**Pull request merged**
