### PR TITLE
Fix the bug that merge from RegExp

### PR DESCRIPTION
**Pull request by XadillaX**
refer issue #410

### CODE REVIEW

**Comment by markstos** [comment]
@lorenwest, this looks good to me.

**Comment by lorenwest** [comment]
Thanks for the fix!

**Comment by XadillaX** [comment]
Hi @lorenwest, I'm just here to ask when to release the new version? I'm waiting to use it.

**Comment by lorenwest** [comment]
Published today @2.26.1 - thanks for the reminder

**Comment by jdmarshall** [comment]
I think this PR likely reintroduced #197 due to a bad else if call.

**Comment by lorenwest** [comment]
#197 was fixed by #198 which included a test to prevent the kind of regression you're suggesting.  Could you add a failing test that describes the issue you're seeing, and would pass once the regression is resolved?

**Pull request merged**
